# -*- coding: utf-8 -*-
"""lab1 python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAdvJdhSkLRQ8Yz6lXdQBwCZmBzzTq1x

. Write a program to convert degree to radian.
Input: 90
Output: 1.57
"""

pi=22/7
degree = float(input(" "))
radian = degree*(pi/180)
print(radian)

"""Write a program to convert radian to degree
Input: 1.57
Output: 90
"""

pi=22/7
radian = float(input(" "))
degree = radian*(180/pi)
print(degree)

"""Write a program to calculate surface volume and area 
of a sphere
Input radius: .75
Output volume: 1.76
Output area: 7.07
"""

pi=22/7
radian = float(input(''))
sur_area = 4 * pi * radian **2
volume = (4/3) * (pi * radian ** 3)
print("Surface Area is: ", sur_area)
print("Volume is: ", volume)

""". Write a program that asks the user to enter two 
integers. Have the program output the two integers and 
the result when the first number entered is raised to the 
power of the second number entered.
Input x=2 
Input y=2
Output: 4


"""

num_1=int(input(" "))
num_2=int(input(" "))
print(num_1**num_2)

""". Write a program to get mean of the degrees of student
(Math = 80, Science =67, Arabic= 65, Studies= 88, 
English = 56
"""

Math = 80
Science =67
Arabic= 65
Studies= 88
English = 56
sum=(Math+Science+Arabic+Studies+English)
print(sum/5)

"""Write a program to solve the second degree equation 
A X^2+B X + C = 0, where the inputs are the 
coefficients A, B and C
"""

import cmath
a = 1
b = 5
c = 6
d = (b**2) - (4*a*c)
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print(sol1,sol2)

"""Write a program to calculate the area of a triangle with 
side a, b and c
"""

a = float(input(' '))  
b = float(input(' '))  
c = float(input(' '))  
s = (a + b + c) / 2  
Area = (s*(s-a)*(s-b)*(s-c)) ** 0.5  
print(Area)

"""Every char is equivalent to number like a=1 ,b=2 and 
so on
Your task when input char print the number equivalent
Input: A
Output: 1
"""

text = input().lower()

for char in text:
    ascii =( ord(char)-96)
    print(char, " ", ascii)

"""Two boys love even number, they want to divide the 
watermelon in such a way that each of the two parts 
weighs even number of kilos, at the same time it is not 
obligatory that the parts are equal, your input number 
of kilos and print if it is can dived between them or not
Input: 8
Output: yes

"""

w=int(input(" "))
if w % 2 == 0 and w!= 2:

	print("yes")
else:
		print("NO")

""" Given two numbers N and M. Print 
the summation of their last digits.
Input N: 12
Input M: 13
Output: 5

"""

num1=int(input(" "))
num_2=int(input(" "))
x=num1%10
y=num_2%10
print(x+y)

