# -*- coding: utf-8 -*-
"""lab2 python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17r3HPLqYxIxDYwzQjvoDq2JTIhty-5ML

The formula to calculate the area of a circumference is 
defined as A = π . R2
. Considering to this problem 
that π = 3.14159:
Calculate the area using the formula given in the problem 
description.
Input r: 2.00
Output: 12.5664
"""

raio = float(input())
area = (raio * raio) * 3.14159 
print(area)

"""Two cars (X and Y) leave in the same direction. The car X 
leaves with a constant speed of 60 km/h and the car Y leaves 
with a constant speed of 90 km / h.
In one hour (60 minutes) the car Y can get a distance of 30 
kilometers from the X car, in other words, it can get away one 
kilometer for each 2 minutes.
Read the distance (in km) and calculate how long it takes (in 
minutes) for the car Y to take this distance in relation to the 
other car.
Input: 30
Output: 60
Input: 7
Output: 14
"""

distance=int(input())
print(distance*2)

"""3. In this problem, the task is to read the number of units of 
product 1, the price for one unit of product 1, the number of 
units of product 2 and the price for one unit of product 2. 
After this, calculate and show the amount to be paid.
Input num1:1
Input price1:5.30
Input: num2:2
Input price2: 5.10
"""

l1 = input().split(" ")
l2 = input().split(" ")
a, b, c = l1
a2, b2,c2 = l2
total = (int(a) * float(b)) +(int(a1) * float(b2))
print(f'VALOR A PAGAR: R$ {total:.2f}')

