# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXrXgeEViz6VHZm6iZzaNH6cpJdAjFeK

---

1. Given a number N and a list A of N numbers. Print 
the absolute summation of these numbers.
Input :4
Inputs of list: 1 2 3 5
Output:11
"""

num = int(input(" "))
hold = num
sum = 1
while num > 0:
        sum = sum + num
        num = num - 1;
    
print(sum)

"""2. Given a number N and a list A of N numbers. Determine if 
the number X exists in array A or not and print its position (0-
index)
Input N: 3
Input list: 3 0 1
Input x: 0
Output: 1
Another input
Input N: 5
Input list: 1 3 0 4 5
Input X: 10
Output:-1 because there isn’t exists
"""

n=int(input(" "))
list=[]
for i in range(n) :
  num=int(input(" "))
  list.append(num)
print(list)
x=int(input(" "))
if x in list :
  print("true")
else:
  print("-1")

"""3. Given a number N and a list A of N numbers .calculate the 
average of this list
Input N:5
Input list: 1 2 3 4 5
Output :3
"""

n = int(input("Enter number"))
sum = 0

for num in range(1, n + 1, 1):
    sum = sum + num
average = sum / n
print(int( average))

"""4. Given a number N and a list A of N numbers .find the 
smallest number in list
Input N: 3
Input list: 3 2 1
Output : 
"""

n=int(input(" "))
list1=[]
for i in range(n) :
  num=int(input(" "))
  list1.append(num)
print(list1)
 

list1.sort()
print( min(list1))

"""5. Given a number N. Print first N numbers of 
the Fibonacci sequence.
Input N: 7
Output: 0 1 1 2 3 5 8 
Search for Fibonacci sequence and know how can
"""



"""6. Write a recursive function to get the sum of integer
Input: 222
Output: 6

"""



"""7. Write a recursive function to get the sum of numbers of
n + (n-1)+(n-2) ……n-x<=0
Input N: 5
Output: 15
"""



"""8. Write a recursive function to get power of number n, e is 
is exponent
Input n: 2
Input e: 3
Output: 8
"""

n=int(input(" "))
e=int(input(" "))
def power(n, e):
    if e== 0:
        return 1
    elif e == 1:
        return n
      
    else:
        return (n*power(n, e-1))
  
print(power(n, e))

3