# -*- coding: utf-8 -*-
"""lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KXeV6z-GZ5DeK3VcakQBlQjWIPvXCTb

1. Create a Vehicle class with max speed and number of cylinder attributes
"""

class Vehicle:
    def __init__(self, max_speed, cylinder):
        self.max_speed = max_speed
        self. cylinder =  cylinder
        
        
car = Vehicle(6, 4)
print(car.max_speed, car.cylinder)

"""2. Write a program that defines a triangle class with a constructor that 
gives value to width and height. That calculate the area of the triangle 
use area (). 
"""

class triangle:
    

  def _init_(self,a,b):
    self.a = float(a)
    self.b = float(b)
a= input("width=")
b= input("height=")
class area(triangle):
    def get_area(self,a,b):
        s =(self.a*self.b)/2
        return s  
t = area()
print(t.area())

3

"""3. Create a program to manage a photo book using object-oriented 
programming.
To start, create a class called PhotoBook with an attribute numPages of 
type int . It must also have a method GetNumberPages that will return the 
number of photo book pages.

"""

